spring:
  profiles:
    active: local

---

spring:
  profiles: local
  h2:
    db:
      tcpPort: 8080
  datasource:
    platform: h2
    jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop
