spring:
  profiles:
    active: dev
---
spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
jwt:
  secret-key: jwtlocalkey
npm:
  path: /Users/kyunam/Documents/workspace-intelliJ/spring-boot-angular-board/src/main/webapp

---
spring:
  profiles: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
jwt:
  secret-key: jwtdevlopkey

---
spring:
  profiles:
    include: real-db